using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class BirthCallAudioConsts
{
	public const string Baby_Cries = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Baby_Cries.mp3";
	public const string Callers_Panic_What_Do_We_Do = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Callers_Panic_What_Do_We_Do.mp3";
	public const string Caller_Birth = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Caller_Birth.mp3";
	public const string Dispatcher_Baby_Crying_Breathing_Question = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Baby_Crying_Breathing_Question.mp3";
	public const string Dispatcher_Baby_Slippery_Instruction = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Baby_Slippery_Instruction.mp3";
	public const string Dispatcher_Can_We_See_Baby_Question = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Can_We_See_Baby_Question.mp3";
	public const string Dispatcher_Check_On_Caller_Instruction = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Check_On_Caller_Instruction.mp3";
	public const string Dispatcher_Corridors_Baby_Slippery_Instruction = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Corridors_Baby_Slippery_Instruction.mp3";
	public const string Dispatcher_Corridors_Can_We_See_Baby = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Corridors_Can_We_See_Baby.mp3";
	public const string Dispatcher_Corridor_Asks_Mothers_Age = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Corridor_Asks_Mothers_Age.mp3";
	public const string Dispatcher_Corridor_Ask_How_Many_Weeks_Pregant_Age_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Corridor_Ask_How_Many_Weeks_Pregant_Age_Branch.mp3";
	public const string Dispatcher_Corridor_Caller_With_Partner = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Corridor_Caller_With_Partner.mp3";
	public const string Dispatcher_Corridor_Mothers_Age_Weeks_Pregnant_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Corridor_Mothers_Age_Weeks_Pregnant_Branch.mp3";
	public const string Dispatcher_Corridor_Tell_Me_Whats_Happened = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Corridor_Tell_Me_Whats_Happened.mp3";
	public const string Dispatcher_Final_Instructions_Instruction = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Final_Instructions_Instruction.mp3";
	public const string Dispatcher_Interrupts_Caller_Again = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Interrupts_Caller_Again.mp3";
	public const string Dispatcher_Interrupts_For_Information = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Interrupts_For_Information.mp3";
	public const string Dispatcher_Paramedics_Arrived_Question = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Paramedics_Arrived_Question.mp3";
	public const string Dispatcher_Prompts_To_Ask_Age = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Prompts_To_Ask_Age.mp3";
	public const string Dispatcher_Prompts_To_Ask_How_Many_Weeks_Pregnant_Age_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Prompts_To_Ask_How_Many_Weeks_Pregnant_Age_Branch.mp3";
	public const string Dispatcher_Prompts_To_Ask_Mothers_Age_Weeks_Pregnant_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Prompts_To_Ask_Mothers_Age_Weeks_Pregnant_Branch.mp3";
	public const string Dispatcher_Ready_Question = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Ready_Question.mp3";
	public const string Dispatcher_Rub_Babys_Back_Instruction = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Rub_Babys_Back_Instruction.mp3";
	public const string Dispatcher_Say_Congratulations_Instruction = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Say_Congratulations_Instruction.mp3";
	public const string Dispatcher_Send_Ambulance_Question = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Send_Ambulance_Question.mp3";
	public const string Dispatcher_Where_Are_They_Now_Question = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Where_Are_They_Now_Question.mp3";
	public const string Dispatcher_Where_To_Hold_Baby_Instruction = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Dispatcher_Where_To_Hold_Baby_Instruction.mp3";
	public const string Paramedics_Arrive = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Paramedics_Arrive.mp3";
	public const string Player_Asks_How_Many_Weeks_Pregnant_Age_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Asks_How_Many_Weeks_Pregnant_Age_Branch.mp3";
	public const string Player_Asks_How_Many_Weeks_Pregnant_Weeks_Pregnant_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Asks_How_Many_Weeks_Pregnant_Weeks_Pregnant_Branch.mp3";
	public const string Player_Asks_Mothers_age_Age_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Asks_Mothers_age_Age_Branch.mp3";
	public const string Player_Asks_Mothers_Age_Weeks_Pregnant_Branch = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Asks_Mothers_Age_Weeks_Pregnant_Branch.mp3";
	public const string Player_Baby_Crying_Breathing_Question_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Baby_Crying_Breathing_Question_Correct.mp3";
	public const string Player_Baby_Slippery_Instruction_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Baby_Slippery_Instruction_Correct.mp3";
	public const string Player_Baby_Slippery_Instruction_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Baby_Slippery_Instruction_Incorrect.mp3";
	public const string Player_Boy_Or_Girl_Question = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Boy_Or_Girl_Question.mp3";
	public const string Player_Caller_With_Partner_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Caller_With_Partner_Correct.mp3";
	public const string Player_Caller_With_Partner_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Caller_With_Partner_Incorrect.mp3";
	public const string Player_Can_We_See_Baby_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Can_We_See_Baby_Correct.mp3";
	public const string Player_Can_We_See_Baby_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Can_We_See_Baby_Incorrect.mp3";
	public const string Player_Check_On_Caller_Shout = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Check_On_Caller_Shout.mp3";
	public const string Player_Congratulations_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Congratulations_Correct.mp3";
	public const string Player_Is_Anything_Wrong_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Is_Anything_Wrong_Correct.mp3";
	public const string Player_Paramedics_Arrived_Question_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Paramedics_Arrived_Question_Correct.mp3";
	public const string Player_Paramedics_Arrived_Question_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Paramedics_Arrived_Question_Incorrect.mp3";
	public const string Player_Ready_No = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Ready_No.mp3";
	public const string Player_Ready_Yes = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Ready_Yes.mp3";
	public const string Player_Rub_Babys_Back_Instruction_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Rub_Babys_Back_Instruction_Correct.mp3";
	public const string Player_Rub_Babys_Back_Instruction_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Rub_Babys_Back_Instruction_Incorrect.mp3";
	public const string Player_Send_Ambulance_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Send_Ambulance_Correct.mp3";
	public const string Player_Send_Ambulance_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Send_Ambulance_Incorrect.mp3";
	public const string Player_Stay_On_The_Line_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Stay_On_The_Line_Correct.mp3";
	public const string Player_Stay_On_The_Line_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Stay_On_The_Line_Incorrect.mp3";
	public const string Player_Tell_Me_Whats_Happened_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Tell_Me_Whats_Happened_Correct.mp3";
	public const string Player_Tell_Me_Whats_Happened_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Tell_Me_Whats_Happened_Incorrect.mp3";
	public const string Player_Where_Are_They_Now_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Where_Are_They_Now_Correct.mp3";
	public const string Player_Where_Are_They_Now_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Where_Are_They_Now_Incorrect.mp3";
	public const string Player_Where_To_Hold_Baby_Instruction_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Where_To_Hold_Baby_Instruction_Correct.mp3";
	public const string Player_Where_To_Hold_Baby_Instruction_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Player_Where_To_Hold_Baby_Instruction_Incorrect.mp3";
	public const string Well_Done_Correct = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Well_Done_Correct.mp3";
	public const string Well_Done_Incorrect = "https://s3-eu-west-1.amazonaws.com/rtg-dispatcher/birth-call/Well_Done_Incorrect.mp3";
}